---
  # Update network settings for a host. should be idempotent
  #
  - name: Create backup dir for ifcfg scripts to avoid accidental execution
    file:
      path: /home/{{ansible_user}}/backup
      state: directory
    tags:
      - prep

  - name: Move ifcfg script
    include_role:
      name: mv
      #private: True
    vars:
      source: "{{ ifcfgDir }}/ifcfg-{{ interface }}"
      destination: "/home/{{ansible_user}}/backup/ifcfg-{{ interface }}"
    tags:
      - netscripts

  - name: Update NetworkManager to use keyfile plugin
    ini_file:
      path: /etc/NetworkManager/NetworkManager.conf
      section: main
      option: plugins
      value: keyfile
      backup: yes
      create: no
    notify:
      - restart NetworkManager
      - wait for new network settings
    tags:
      - prep

  - name: Apply interface config
    template:
      src: "{{ ConfType }}.j2"
      dest: "{{ NewConfigDir }}/ansible_generated-{{ ID }}.conf"
      mode: 0600
    notify:
      - restart NetworkManager
      - reload network interface
      - bring interface up
      - wait for new network settings
    tags:
      - configuration
