---
  # restart NetworkManmager
  #
  - name: reload network interface
    shell: "nmcli con load {{ NewConfigDir }}/ansible_generated-{{ ID }}.conf"

  - name: restart NetworkManager
    service:
      name: NetworkManager
      state: restarted
    async: 20
    poll: 0

  - name: bring interface up
    shell: "nmcli con up {{ ID }}"
  - name: Reset ssh connection 3
    meta: reset_connection

  - name: wait for new network settings
    become: no
    local_action:
      module: wait_for host={{ ansible_ssh_host | default(inventory_hostname) }} port=22 delay=10 timeout=300
