---
  interface: enp0s8
  newaddress: fd01:1:1:1::100/64
  ifcfgDir: /etc/sysconfig/network-scripts
  NewConfigDir: /etc/NetworkManager/system-connections
  ConfType: static6 # also try dhcp4 for auto IPv4
  ID: "{{ inventory_hostname }}"
